project_name: bbdb
before:
  hooks:
    - go mod tidy
builds:
  - binary: bbdb
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/ewhanson/bbdb/pbaddons.Version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
